language: rust

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build -v
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then cargo test -v; fi
  - |
    if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      rustup target add wasm32-unknown-unknown --toolchain nightly
      cargo install wasm-bindgen-cli --vers "0.2.50"
      cargo test -v --target wasm32-unknown-unknown
    fi
  - |
    if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then
      rustup component add rustfmt
      cargo fmt --all -- --check
    fi
  - cargo doc -v
