[package]
name = "imageproc"
version = "0.19.0"
authors = ["theotherphil"]
edition = "2018"
license = "MIT"
description = "Image processing operations"
readme = "README.md"
repository = "https://github.com/image-rs/imageproc.git"
homepage = "https://github.com/image-rs/imageproc"
exclude = ["examples/*.ttf"]

[features]
default = []
property-testing = [ "quickcheck" ]
display-window = ["sdl2"]

[dependencies]
conv = "0.3.1"
image = { version = "0.22.2", default-features = false }
itertools = "0.7.0"
num = "0.2.0"
rand = "0.6.5"
rusttype = "0.7"
rayon = "1.0"
quickcheck = { version = "0.8", optional = true }
sdl2 = { version = "0.32", optional = true, default-features = false, features = ["bundled"] }
rulinalg = "0.4.2"

[dev-dependencies]
assert_approx_eq = "1.0.0"
image = "0.22.2"
quickcheck = "0.8"
wasm-bindgen-test = "0.2"

[package.metadata.docs.rs]
all-features = true

[profile.release]
opt-level = 3
debug = true

[profile.bench]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
